name: Actions - Build / Deployments
run-name: Build / Deployments
on: 
  push:
    branches: 
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Init of Context.'
        run: echo 'Branch [ ${{ github.ref }} ].'
        run: echo 'Repo [ ${{ github.repository }} ].'
        run: echo 'Author [ ${{ github.actor }} ].'
      - name: 'Check out Repo.'
        uses: actions/checkout@v3
      - name: 'Result.'
        run: echo 'The code of [ ${{ github.repository }} ] has been cloned to the runner.'
        run: echo 'Etat [ ${{ job.status }} ].'