# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Actions - Compile
run-name: Compile

on:
  push:
    branches:
      - master
      - develop
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install, test and build
        run: |
          npm ci
          npm run build
          npm pack
      - name: archive compiled packed app
        uses: actions/upload-artifact@v3
        with:
          name: packed
          path: |
            *.tgz
      